# Configuration du serveur
server:
  port: 8092

# Configuration Keycloak
keycloak:
  realm: spring-mvc2-realm
  auth-server-url: "http://localhost:8181/"
  resource: spring-mvc-2
  public-client: true
  principal-attribute: name

# Configuration de l'application Spring
spring:
  application:
    name: Spring Web MVC

  # Configuration de la source de données
  datasource:
    url: jdbc:mysql://localhost:3306/springmvc2?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuration JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuration Thymeleaf
  thymeleaf:
    cache: false

